apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: jaeger-exporter
  name: jaeger-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: jaeger-exporter   #promethues 发现的端口
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: jaeger-exporter

